////
////  trash.swift
////  Calculator
////
////  Created by Арсений on 11/6/23.
////
//
//import Foundation
//zeroButton.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
//zeroButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0),
//oneButton.leadingAnchor.constraint(equalTo: zeroButton.trailingAnchor, constant: 0),
//oneButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0),
//twoButton.leadingAnchor.constraint(equalTo: oneButton.trailingAnchor, constant: 0),
//twoButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0),
//threeButton.leadingAnchor.constraint(equalTo: twoButton.trailingAnchor, constant: 0),
//threeButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0),
//plusButton.leadingAnchor.constraint(equalTo: threeButton.trailingAnchor, constant: 0),
//plusButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0),
//fourButton.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
//fourButton.bottomAnchor.constraint(equalTo: zeroButton.topAnchor, constant: 0),
//fiveButton.leadingAnchor.constraint(equalTo: fourButton.trailingAnchor, constant: 0),
//fiveButton.bottomAnchor.constraint(equalTo: oneButton.topAnchor, constant: 0),
//sixButton.leadingAnchor.constraint(equalTo: fiveButton.trailingAnchor, constant: 0),
//sixButton.bottomAnchor.constraint(equalTo: twoButton.topAnchor, constant: 0),
//sevenButton.leadingAnchor.constraint(equalTo: sixButton.trailingAnchor, constant: 0),
//sevenButton.bottomAnchor.constraint(equalTo: threeButton.topAnchor, constant: 0),
//minusButton.leadingAnchor.constraint(equalTo: sevenButton.trailingAnchor, constant: 0),
//minusButton.bottomAnchor.constraint(equalTo: plusButton.topAnchor, constant: 0),
//eightButton.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
//eightButton.bottomAnchor.constraint(equalTo: fourButton.topAnchor, constant: 0),
//resultLabel.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
//resultLabel.bottomAnchor.constraint(equalTo: eightButton.topAnchor, constant: 0),
//resultLabel.widthAnchor.constraint(equalToConstant: 90),
//resultLabel.heightAnchor.constraint(equalToConstant: 90),
//nineButton.leadingAnchor.constraint(equalTo: eightButton.trailingAnchor, constant: 0),
//nineButton.bottomAnchor.constraint(equalTo: fiveButton.topAnchor, constant: 0),
//multiplyButton.bottomAnchor.constraint(equalTo: minusButton.topAnchor, constant: 0),
//multiplyButton.leadingAnchor.constraint(equalTo: nineButton.trailingAnchor, constant: 60),
//percentButton.leadingAnchor.constraint(equalTo: resultLabel.trailingAnchor, constant: 30),
//percentButton.bottomAnchor.constraint(equalTo: multiplyButton.topAnchor, constant: 0),
//equalButton.leadingAnchor.constraint(equalTo: resultLabel.trailingAnchor, constant: 30),
//equalButton.bottomAnchor.constraint(equalTo: percentButton.topAnchor, constant: 0)


//mainStack.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 0),
//mainStack.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 0),
//mainStack.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: 0),
//mainStack.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: 0),
//zeroButton.leadingAnchor.constraint(equalTo: mainStack.leadingAnchor, constant: 0),
//zeroButton.bottomAnchor.constraint(equalTo: mainStack.bottomAnchor, constant: 0),
//oneButton.leadingAnchor.constraint(equalTo: zeroButton.trailingAnchor, constant: 0),
//oneButton.bottomAnchor.constraint(equalTo: mainStack.bottomAnchor, constant: 0),
//twoButton.leadingAnchor.constraint(equalTo: oneButton.trailingAnchor, constant: 0),
//twoButton.bottomAnchor.constraint(equalTo: mainStack.bottomAnchor, constant: 0),
//threeButton.leadingAnchor.constraint(equalTo: twoButton.trailingAnchor, constant: 0),
//threeButton.bottomAnchor.constraint(equalTo: mainStack.bottomAnchor, constant: 0),
//plusButton.leadingAnchor.constraint(equalTo: threeButton.trailingAnchor, constant: 0),
//plusButton.bottomAnchor.constraint(equalTo: mainStack.bottomAnchor, constant: 0),
//fourButton.leadingAnchor.constraint(equalTo: mainStack.leadingAnchor, constant: 0),
//fourButton.bottomAnchor.constraint(equalTo: zeroButton.topAnchor, constant: 0),
//fiveButton.leadingAnchor.constraint(equalTo: fourButton.trailingAnchor, constant: 0),
//fiveButton.bottomAnchor.constraint(equalTo: oneButton.topAnchor, constant: 0),
//sixButton.leadingAnchor.constraint(equalTo: fiveButton.trailingAnchor, constant: 0),
//sixButton.bottomAnchor.constraint(equalTo: twoButton.topAnchor, constant: 0),
//sevenButton.leadingAnchor.constraint(equalTo: sixButton.trailingAnchor, constant: 0),
//sevenButton.bottomAnchor.constraint(equalTo: threeButton.topAnchor, constant: 0),
//minusButton.leadingAnchor.constraint(equalTo: sevenButton.trailingAnchor, constant: 0),
//minusButton.bottomAnchor.constraint(equalTo: plusButton.topAnchor, constant: 0),
//eightButton.leadingAnchor.constraint(equalTo: mainStack.leadingAnchor, constant: 0),
//eightButton.bottomAnchor.constraint(equalTo: fourButton.topAnchor, constant: 0),
//resultLabel.leadingAnchor.constraint(equalTo: main.leadingAnchor, constant: 0),
//resultLabel.bottomAnchor.constraint(equalTo: eightButton.topAnchor, constant: 0),
//resultLabel.widthAnchor.constraint(equalToConstant: 90),
//resultLabel.heightAnchor.constraint(equalToConstant: 90),
//nineButton.leadingAnchor.constraint(equalTo: eightButton.trailingAnchor, constant: 0),
//nineButton.bottomAnchor.constraint(equalTo: fiveButton.topAnchor, constant: 0),
//multiplyButton.bottomAnchor.constraint(equalTo: minusButton.topAnchor, constant: 0),
//multiplyButton.leadingAnchor.constraint(equalTo: nineButton.trailingAnchor, constant: 60),
//percentButton.leadingAnchor.constraint(equalTo: resultLabel.trailingAnchor, constant: 30),
//percentButton.bottomAnchor.constraint(equalTo: multiplyButton.topAnchor, constant: 0),
//equalButton.leadingAnchor.constraint(equalTo: resultLabel.trailingAnchor, constant: 30),
//equalButton.bottomAnchor.constraint(equalTo: percentButton.topAnchor, constant: 0)
